var i18n = {
    "AF": "Afghánistán",
    "AL": "Albánie",
    "DZ": "Alžírsko",
    "AS": "Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarktida",
    "AG": "Antigua a Barbuda",
    "AR": "Argentina",
    "AM": "Arménie",
    "AW": "Aruba",
    "AU": "Austrálie",
    "AT": "Rakousko",
    "AZ": "Ázerbájdžán",
    "BS": "Bahamy",
    "BH": "Bahrajn",
    "BD": "Bangladéš",
    "BB": "Barbados",
    "BY": "Bělorusko",
    "BE": "Belgie",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermudy",
    "BT": "Bhútán",
    "BO": "Bolívie",
    "BA": "Bosna a Hercegovina",
    "BW": "Botswana",
    "BV": "Isola Bouvet",
    "BR": "Brazílie",
    "IO": "Britské indickooceánské území",
    "BN": "Brunej",
    "BG": "Bulharsko",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Kambodža",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CV": "Kapverdy",
    "KY": "Kajmanské ostrovy",
    "CF": "Středoafrická republika",
    "TD": "Čad",
    "CL": "Chile",
    "CN": "Čína",
    "CX": "Vánoční ostrov",
    "CC": "Kokosové ostrovy",
    "CO": "Kolumbie",
    "KM": "Komory",
    "CG": "Kongo",
    "CD": "Demokratická republika Kongo",
    "CK": "Cookovy ostrovy",
    "CR": "Kostarika",
    "CI": "Pobřeží slonoviny",
    "HR": "Chorvatsko ",
    "CU": "Kuba",
    "CY": "Kypr",
    "CZ": "Česká republika",
    "DK": "Dánsko",
    "DJ": "Džíbútí",
    "DM": "Dominika",
    "DO": "Dominikánská republika",
    "EC": "Ekvádor",
    "EG": "Egypt",
    "SV": "Salvador",
    "GQ": "Rovníková Guinea",
    "ER": "Eritrea",
    "EE": "Estonsko",
    "ET": "Etiopie",
    "FK": "Falklandy ( Malvíny)",
    "FO": "Faerské ostrovy",
    "FJ": "Fidž",
    "FI": "Fidži",
    "FR": "Francie",
    "GF": "Francouzská Guyana",
    "PF": "Francouzská Polynésie",
    "TF": "Francouzská jižní a antarktická území",
    "GA": "Gabon",
    "GM": "Gambie",
    "GE": "Gruzie",
    "DE": "Německo",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Řecko",
    "GL": "Grónsko",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heardův ostrov",
    "VA": "Vatikán",
    "HN": "Honduras",
    "HK": "Hongkong",
    "HU": "Maďarsko",
    "IS": "Island",
    "IN": "Indie",
    "ID": "Indonésie",
    "IR": "Írán",
    "IQ": "Irák",
    "IE": "Irsko",
    "IL": "Izrael",
    "IT": "Itálie",
    "JM": "Jamajka",
    "JP": "Japonsko",
    "JO": "Jordán",
    "KZ": "Kazachstán",
    "KE": "Keňa",
    "KI": "Kiribati",
    "KP": "Korejská lidově demokratická republika",
    "KR": "Korejská republika",
    "KW": "Kuvajt",
    "KG": "Kyrgyzstán",
    "LA": "Laos",
    "LV": "Lotyšsko",
    "LB": "Libanon",
    "LS": "Lesotho",
    "LR": "Libérie",
    "LY": "Libye",
    "LI": "Lichtenštejnsko",
    "LT": "Litva",
    "LU": "Lucembursko",
    "MO": "Macao",
    "MK": "Makedonie",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "MY": "Malajsie",
    "MV": "Maledivy",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshallovy ostrovy",
    "MQ": "Martinica",
    "MR": "Mauritánie",
    "MU": "Mauricius ",
    "YT": "Mayotte",
    "MX": "Mexiko",
    "FM": "Mikronésie",
    "MD": "Moldavsko",
    "MC": "Monaco",
    "MN": "Mongolsko",
    "MS": "Montserrat",
    "MA": "Maroko",
    "MZ": "Mosambik",
    "MM": "Myanmar",
    "NA": "Namibie",
    "NR": "Nauru",
    "NP": "Nepál",
    "NL": "Nizozemsko",
    "NC": "Nová Kaledonie",
    "NZ": "Nový Zéland",
    "NI": "Nikaragua",
    "NE": "Niger",
    "NG": "Nigérie",
    "NU": "Niue",
    "NF": "Norfolk (ostrov)",
    "MP": "Severní Mariany",
    "NO": "Norsko",
    "OM": "Omán",
    "PK": "Pákistán",
    "PW": "Palau",
    "PS": "Palestinská autonomie",
    "PA": "Panama",
    "PG": "Papua-Nová Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Filipíny",
    "PN": "Pitcairn",
    "PL": "Polsko",
    "PT": "Portugalsko",
    "PR": "Portoriko",
    "QA": "Katar",
    "RE": "Reunion",
    "RO": "Rumunsko",
    "RU": "Rusko",
    "RW": "Rwanda",
    "SH": "St. Helena",
    "KN": "Svatý Kryštof a Nevis",
    "LC": "Svatá Lucie ",
    "PM": "Saint Pierre e Miquelon",
    "VC": "Svatý Vincenc a Grenadiny ",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Saint-Pierre a Miquelon",
    "SA": "Saúdská Arábie",
    "SN": "Senegal",
    "SC": "Seychely",
    "SL": "Sierra Leone",
    "SG": "Singapur",
    "SK": "Slovensko",
    "SI": "Slovinsko",
    "SB": "Šalamounovy ostrovy",
    "SO": "Somálsko",
    "ZA": "Jihoafrická republika",
    "GS": "Jižní Georgie a Jižní Sandwichovy ostrovy",
    "ES": "Španělsko",
    "LK": "Srí Lanka",
    "SD": "Súdán",
    "SR": "Surinam",
    "SJ": "Špicberky a Jan Mayen",
    "SZ": "Svazijsko",
    "SE": "Švédsko",
    "CH": "Švýcarsko",
    "SY": "Sýrie",
    "TW": "Tchaj-wan",
    "TJ": "Tádžikistán",
    "TZ": "Tanzanie",
    "TH": "Thajsko",
    "TL": "Timor Est",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad a Tobago",
    "TN": "Tunisko",
    "TR": "Turecko",
    "TM": "Turkmenistán",
    "TC": "Turks a Caicos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukrajina",
    "AE": "Spojené arabské emiráty",
    "GB": "Spojené království",
    "US": "Spojené státy americké",
    "UM": "Menší odlehlé ostrovy Spojených států amerických",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Britské Panenské ostrovy",
    "VI": "Americké Panenské ostrovy",
    "WF": "Wallis e Futuna",
    "EH": "Západní Sahara",
    "YE": "Jemen",
    "ZM": "Zambiea",
    "ZW": "Zimbabwe",
    "AX": "Isole Åland",
    "BQ": "Caribbean -  Nizozemsko",
    "CW": "Curaçao",
    "GG": "Guernsey",
    "IM": "Isola di Man",
    "JE": "Normanské ostrovy",
    "ME": "Černá Hora",
    "BL": "Saint Barthelemy ( Francouzské Antily )",
    "MF": "Sint Maarten ( francouzská strana )",
    "RS": "Srbsko",
    "SX": "Sint Maarten (holandský strana)",
    "SS": "Súdán Jižní"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
