var i18n = {
	"AF": "Afghanistan",
	"AL": "Albanie",
	"DZ": "Algérie",
	"AS": "Samoa américaines",
	"AD": "Andorre",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarctique",
	"AG": "Antigua-et-Barbuda",
	"AR": "Argentine",
	"AM": "Arménie",
	"AW": "Aruba",
	"AU": "Australie",
	"AT": "Autriche",
	"AZ": "Azerbaïdjan",
	"BS": "Bahamas",
	"BH": "Bahreïn",
	"BD": "Bangladesh",
	"BB": "Barbade",
	"BY": "Biélorussie",
	"BE": "Belgique",
	"BZ": "Belize",
	"BJ": "Bénin",
	"BM": "Bermudes",
	"BT": "Bhoutan",
	"BO": "Bolivie",
	"BA": "Bosnie-Herzégovine",
	"BW": "Botswana",
	"BV": "Ile Bouvet",
	"BR": "Brésil",
	"IO": "Territoire britannique de l'Océan Indien",
	"BN": "Brunei",
	"BG": "Bulgarie",
	"BF": "Burkina Faso",
	"BI": "Burundi",
	"KH": "Cambodge",
	"CM": "Cameroun",
	"CA": "Canada",
	"CV": "Cap-Vert",
	"KY": "Iles Cayman",
	"CF": "République centrafricaine",
	"TD": "Tchad",
	"CL": "Chili",
	"CN": "Chine",
	"CX": "Ile Christmas",
	"CC": "Iles des Cocos (Keeling)",
	"CO": "Colombie",
	"KM": "Comores",
	"CG": "Congo",
	"CD": "République démocratique du Congo",
	"CK": "Iles Cook",
	"CR": "Costa Rica",
	"CI": "Ivory Coast",
	"HR": "Croatia",
	"CU": "Cuba",
	"CY": "Cyprus",
	"CZ": "République tchèque",
	"DK": "Danemark",
	"DJ": "Djibouti",
	"DM": "Dominique",
	"DO": "République dominicaine",
	"EC": "Équateur",
	"EG": "Égypte",
	"SV": "Salvador",
	"GQ": "Guinée équatoriale",
	"ER": "Érythrée",
	"EE": "Estonie",
	"ET": "Éthiopie",
	"FK": "Iles Falkland",
	"FO": "Iles Féroé",
	"FJ": "Iles Fidji",
	"FI": "Finlande",
	"FR": "France",
	"GF": "Guyane française",
	"PF": "Polynésie française",
	"TF": "Terres australes françaises",
	"GA": "Gabon",
	"GM": "Gambie",
	"GE": "Géorgie",
	"DE": "Allemagne",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GR": "Grèce",
	"GL": "Groenland",
	"GD": "Grenade",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GN": "Guinée",
	"GW": "Guinée-Bissao",
	"GY": "Guyana",
	"HT": "Haïti",
	"HM": "Iles Heard et McDonald",
	"VA": "Saint-Siège",
	"HN": "Honduras",
	"HK": "Hong Kong",
	"HU": "Hongrie",
	"IS": "Islande",
	"IN": "Inde",
	"ID": "Indonésie",
	"IR": "Iran",
	"IQ": "Iraq",
	"IE": "Irlande",
	"IL": "Israël",
	"IT": "Italie",
	"JM": "Jamaïque",
	"JP": "Japon",
	"JO": "Jordanie",
	"KZ": "Kazakhstan",
	"KE": "Kenya",
	"KI": "Kiribati",
	"KP": "Corée du Nord",
	"KR": "Corée du sud",
	"KW": "Koweït",
	"KG": "Kirghizistan",
	"LA": "Laos",
	"LV": "Lettonie",
	"LB": "Liban",
	"LS": "Lesotho",
	"LR": "Liberia",
	"LY": "Libye",
	"LI": "Liechtenstein",
	"LT": "Lituanie",
	"LU": "Luxembourg",
	"MO": "Macao",
	"MK": "ex-République yougoslave de Macédoine",
	"MG": "Madagascar",
	"MW": "Malawi",
	"MY": "Malaisie",
	"MV": "Maldives",
	"ML": "Mali",
	"MT": "Malte",
	"MH": "Iles Marshall",
	"MQ": "Martinique",
	"MR": "Mauritanie",
	"MU": "Maurice",
	"YT": "Mayotte",
	"MX": "Mexique",
	"FM": "Micronésie",
	"MD": "Moldavie",
	"MC": "Monaco",
	"MN": "Mongolie",
	"MS": "Montserrat",
	"MA": "Maroc",
	"MZ": "Mozambique",
	"MM": "Birmanie",
	"NA": "Namibia",
	"NR": "Nauru",
	"NP": "Nepal",
	"NL": "Pays-Bas",
	"NC": "Nouvelle-Calédonie",
	"NZ": "Nouvelle-Zélande",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"NU": "Nioué",
	"NF": "Ile Norfolk",
	"MP": "Mariannes du Nord",
	"NO": "Norvège",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PS": "Territoires palestiniens occupés",
	"PA": "Panama",
	"PG": "Papouasie-Nouvelle-Guinée",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Philippines",
	"PN": "Iles Pitcairn",
	"PL": "Pologne",
	"PT": "Portugal",
	"PR": "Porto Rico",
	"QA": "Qatar",
	"RE": "Réunion",
	"RO": "Roumanie",
	"RU": "Russie",
	"RW": "Rwanda",
	"SH": "Sainte-Hélène",
	"KN": "Saint-Christophe-et-Nevis ",
	"LC": "Sainte-Lucie",
	"PM": "Saint-Pierre-et-Miquelon",
	"VC": "Saint-Vincent-et-les-Grenadines",
	"WS": "Samoa",
	"SM": "Saint-Marin",
	"ST": "São Tomé e Príncipe ",
	"SA": "Arabia Saudite",
	"SN": "Sénégal",
	"SC": "Seychelles",
	"SL": "Sierra Leone",
	"SG": "Singapour",
	"SK": "Slovaquie",
	"SI": "Slovénie",
	"SB": "Iles Salomon",
	"SO": "Somalie",
	"ZA": "Afrique du Sud",
	"GS": "Iles Géorgie du Sud et Sandwich du Suds",
	"ES": "Espagne",
	"LK": "Sri Lanka",
	"SD": "Soudan",
	"SR": "Suriname",
	"SJ": "Iles Svalbard et Jan Mayen",
	"SZ": "Swaziland",
	"SE": "Suède",
	"CH": "Suisse",
	"SY": "Syrie",
	"TW": "Taïwan",
	"TJ": "Tadjikistan",
	"TZ": "Tanzanie",
	"TH": "Thaïlande",
	"TL": "Timor Oriental",
	"TG": "Togo",
	"TK": "Tokélaou",
	"TO": "Tonga",
	"TT": "Trinidad-et-Tobago ",
	"TN": "Tunisie",
	"TR": "Turquie",
	"TM": "Turkménistan",
	"TC": "Iles Turks-et-Caicos",
	"TV": "Tuvalu",
	"UG": "Ouganda",
	"UA": "Ukraine",
	"AE": "Émirats arabes unis",
	"GB": "Royaume-Uni",
	"US": "États-Unis",
	"UM": "Iles mineures éloignées des États-Unis",
	"UY": "Uruguay",
	"UZ": "Ouzbékistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Viêtnam",
	"VG": "Britse Maagdeneilanden",
	"VI": "Amerikaanse Maagdeneilanden",
	"WF": "Wallis en Futuna",
	"EH": "Westelijke Sahara",
	"YE": "Jemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
	"AX": "Åland Iles",
	"BQ": "Pays-Bas caribéens",
	"CW": "Curaçao",
	"GG": "Guernsey",
	"IM": "Île de Man",
	"JE": "Jersey",
	"ME": "Montenegro",
	"BL": "Territorial collectivity of Saint-Barthélemy",
	"MF": "Saint-Barthélemy (Antilles françaises)",
	"RS": "Serbie",
	"SX": "Saint-Martin (Royaume des Pays-Bas)",
	"SS": "Soudan du Sud"
	};

	exports.i18n = function() {
		"use strict";
		return i18n;
	};
