var i18n = {
    "AF": "Afganisztán",
    "AL": "Albánia",
    "DZ": "Algéria",
    "AS": "Amerikai Szamoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarktisz",
    "AG": "Antigua és Barbuda",
    "AR": "Argentina",
    "AM": "Örményország",
    "AW": "Aruba",
    "AU": "Ausztrália",
    "AT": "Ausztria",
    "AZ": "Azerbajdzsán",
    "BS": "Bahama-szigetek",
    "BH": "Bahrein",
    "BD": "Banglades",
    "BB": "Barbados",
    "BY": "Belorusszia",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhután",
    "BO": "Bolivia",
    "BA": "Bosznia-Hercegovina",
    "BW": "Botswana",
    "BV": "Bouvet-sziget",
    "BR": "Brazília",
    "IO": "Brit Indiai-óceáni Terület",
    "BN": "Brunei Darussalam",
    "BG": "Bulgária",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Kambodzsa",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CV": "Zöld-foki-szigetek",
    "KY": "Kajmán-szigetek",
    "CF": "Közép-Afrikai Köztársaság",
    "TD": "Csád",
    "CL": "Chile",
    "CN": "Kina",
    "CX": "Karácsony-sziget",
    "CC": "Kókusz-szigetek (Keeling-szigetek)",
    "CO": "Kolombia",
    "KM": "Comore-szigetek",
    "CG": "Kongó",
    "CD": "Kongói Demokratikus Köztársaság",
    "CK": "Cook-szigetek",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire (Elefántcsontpart)",
    "HR": "Horvátország",
    "CU": "Kuba",
    "CY": "Ciprus",
    "CZ": "Cseh Köztársaság",
    "DK": "Dánia",
    "DJ": "Dzsibuti",
    "DM": "Dominika",
    "DO": "Dominikai Köztársaság",
    "EC": "Ecuador",
    "EG": "Egyiptom",
    "SV": "El Salvador",
    "GQ": "Egyenlítõi Guinea",
    "ER": "Eritrea",
    "EE": "Észtország",
    "ET": "Etiópia",
    "FK": "Falkland-szigetek (Malvin-szigetek)",
    "FO": "Feröer-szigetek",
    "FJ": "Fidzsi",
    "FI": "Finnország",
    "FR": "Franciaország",
    "GF": "Francia Guyana",
    "PF": "Francia Polinézia",
    "TF": "Francia Déli Területek",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Németország",
    "GH": "Ghána",
    "GI": "Gibraltár",
    "GR": "Görögország",
    "GL": "Grönland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Bissau-Guinea",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard- és McDonald-szigetek",
    "VA": "Vatikán",
    "HN": "Honduras",
    "HK": "Hongkong (k.k.t.)",
    "HU": "Magyarország",
    "IS": "Izland",
    "IN": "India",
    "ID": "Indonézia",
    "IR": "Irán (Iszlám Köztársaság)",
    "IQ": "Irak",
    "IE": "Írország",
    "IL": "Izrael",
    "IT": "Olaszország",
    "JM": "Jamaica",
    "JP": "Japán",
    "JO": "Jordánia",
    "KZ": "Kazahsztán",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Koreai Népi Demokratikus Köztársaság",
    "KR": "Koreai Köztársaság",
    "KW": "Kuwait",
    "KG": "Kirgizisztán",
    "LA": "Lao Népi Demokratikus Köztársaság",
    "LV": "Lettország",
    "LB": "Libanon",
    "LS": "Lesotho",
    "LR": "Libéria",
    "LY": "Libia",
    "LI": "Liechtenstein",
    "LT": "Litvánia",
    "LU": "Luxemburg",
    "MO": "Makaó (k.k.t.)",
    "MK": "Macedónia (volt jugoszláv köztársaság)",
    "MG": "Madagaszkár",
    "MW": "Malawi",
    "MY": "Malajzia",
    "MV": "Maldív-szigetek",
    "ML": "Mali",
    "MT": "Málta",
    "MH": "Marshall-szigetek",
    "MQ": "Martinique",
    "MR": "Mauritánia",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexikó",
    "FM": "Mikronéziai Szövetségi Államok",
    "MD": "Moldva",
    "MC": "Monaco",
    "MN": "Mongólia",
    "MS": "Montserrat",
    "MA": "Marokkó",
    "MZ": "Mozambik",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepál",
    "NL": "Hollandia",
    "NC": "Új-Kaledónia",
    "NZ": "Új-Zéland",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigéria",
    "NU": "Niue",
    "NF": "Norfolk-sziget",
    "MP": "Észak-Mariana-szigetek",
    "NO": "Norvégia",
    "OM": "Omán",
    "PK": "Pakisztán",
    "PW": "Palau",
    "PS": "Palesztina",
    "PA": "Panama",
    "PG": "Papua Nuova Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Fülöp-szigetek",
    "PN": "Pitcairn",
    "PL": "Lengyelország",
    "PT": "Portugália",
    "PR": "Puerto Rico",
    "QA": "Katar",
    "RE": "Reunion",
    "RO": "Románia",
    "RU": "Orosz Föderáció",
    "RW": "Ruanda",
    "SH": "Szent Ilona",
    "KN": "Saint Kitts és Nevis",
    "LC": "Szent Lucia",
    "PM": "St. Pierre és Miquelon",
    "VC": "Saint Vincent és Grenadines",
    "WS": "Szamoa",
    "SM": "San Marino",
    "ST": "Sao Tome és Principe",
    "SA": "Szaúd-Arábia",
    "SN": "Szenegál",
    "SC": "Seychelle-szigetek",
    "SL": "Sierra Leone",
    "SG": "Szingapúr",
    "SK": "Szlovákia (Szlovák Köztársaság)",
    "SI": "Szlovénia",
    "SB": "Salamon-szigetek",
    "SO": "Szomália",
    "ZA": "Dél-Afrika",
    "GS": "Dél-Georgia és a Dél-Sandwich-szigetek",
    "ES": "Spanyolország",
    "LK": "Sri Lanka",
    "SD": "	Szudán",
    "SR": "Suriname",
    "SJ": "Svalbard- és Jan Mayen-szigetek",
    "SZ": "Szváziföld",
    "SE": "Svédország",
    "CH": "Svájc",
    "SY": "Szíriai Arab Köztársaság",
    "TW": "Tajvan",
    "TJ": "Tádzsikisztán",
    "TZ": "Tanzániai Egyesült Köztársaság",
    "TH": "Thaiföld",
    "TL": "Kelet-Timor",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad és Tobago",
    "TN": "Tunézia",
    "TR": "Törökország",
    "TM": "Türkmenisztán",
    "TC": "Turks- és Caicos-szigetek",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukrajna",
    "AE": "Egyesült Arab Emirátusok",
    "GB": "Egyesült Királyság",
    "US": "Egyesült Államok",
    "UM": "Egyesült Államok külsõ szigetei",
    "UY": "Uruguay",
    "UZ": "Üzbegisztán",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnám",
    "VG": "Brit Virgin-szigetek",
    "VI": "Amerikai Virgin-szigetek",
    "WF": "Wallis és Futuna",
    "EH": "Nyugat Szahara",
    "YE": "Jemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "AX": "Isole Åland",
    "BQ": "Karib- Hollandia",
    "CW": "Curaçao",
    "GG": "Guernsey",
    "IM": "Isle of Man",
    "JE": "Jersey",
    "ME": "Montenegró",
    "BL": "Saint- Barthelemy ( Francia Nyugat -India)",
    "MF": "Sint Maarten ( francia oldalról )",
    "RS": "Szerbia",
    "SX": "Sint Maarten ( holland oldalon )",
    "SS": "Dél-Szudán"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
