var i18n = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "Samoa Americane",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antartide",
    "AG": "Antigua e Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Bielorussia",
    "BE": "Belgio",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia ed Erzegovina",
    "BW": "Botswana",
    "BV": "Isola Bouvet",
    "BR": "Brasile",
    "IO": "Territori Britannici dell'Oceano Indiano",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambogia",
    "CM": "Camerun",
    "CA": "Canada",
    "CV": "Capo Verde",
    "KY": "Isole Cayman",
    "CF": "Centrafrica",
    "TD": "Ciad",
    "CL": "Cile",
    "CN": "Cina",
    "CX": "Isola Christmas",
    "CC": "Isole Cocos",
    "CO": "Colombia",
    "KM": "Comore",
    "CG": "Congo (R.d.)",
    "CD": "Congo (Rep.)",
    "CK": "Isole Cook",
    "CR": "Congo (Rep.)",
    "CI": "Costa d'Avorio",
    "HR": "Croazia",
    "CU": "Cuba",
    "CY": "Cipro",
    "CZ": "Repubblica Ceca",
    "DK": "Danimarca",
    "DJ": "Gibuti",
    "DM": "Dominica",
    "DO": "Dominicana (Rep.)",
    "EC": "Ecuador",
    "EG": "Egitto",
    "SV": "El Salvador",
    "GQ": "Guinea Equatoriale",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Etiopia",
    "FK": "Isole Falkland (Malvinas)",
    "FO": "Isole Faroe",
    "FJ": "Isole Fiji",
    "FI": "Finlandia",
    "FR": "Francia",
    "GF": "Guyana Francese",
    "PF": "Polinesia Francese",
    "TF": "Terre australi e antartiche francesi",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germania",
    "GH": "Ghana",
    "GI": "Gibilterra",
    "GR": "Grecia",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadalupa",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Isole Heard e McDonald",
    "VA": "Santa Sede, Vaticano (Citta' del)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Ungheria",
    "IS": "Islanda",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Repubblica islamica dell'Iran",
    "IQ": "Iraq",
    "IE": "Irlanda",
    "IL": "Israele",
    "IT": "Italia",
    "JM": "Giamaica",
    "JP": "Giappone",
    "JO": "Giordania",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Corea (R.d.p)",
    "KR": "Corea (Rep.)",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Lettonia",
    "LB": "Libano",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libia",
    "LI": "Liechtenstein",
    "LT": "Lituania",
    "LU": "Lussemburgo",
    "MO": "Macao",
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malesia",
    "MV": "Maldive",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Isole Marshall",
    "MQ": "Martinica",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Messico",
    "FM": "Stati federati di Micronesia",
    "MD": "Micronesia (Isole)",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Marocco",
    "MZ": "Mozambico",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Paesi Bassi",
    "NC": "Nuova Caledonia",
    "NZ": "Nuova Zelanda",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Isola Norfolk",
    "MP": "Isole Marianne Settentrionali",
    "NO": "Norvegia",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Autorità Palestinese",
    "PA": "Panama",
    "PG": "Papua Nuova Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Filippine",
    "PN": "Isole Pitcairn",
    "PL": "Polonia",
    "PT": "Portogallo",
    "PR": "Porto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Ruanda",
    "SH": "Sant'Elena",
    "KN": "St. Kitts e Nevis",
    "LC": "Santa Lucia",
    "PM": "Saint Pierre e Miquelon",
    "VC": "Saint Vincent e Grenadine",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome e Principe",
    "SA": "Arabia Saudita",
    "SN": "Senegal",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovacchia",
    "SI": "Slovenia",
    "SB": "Salomone",
    "SO": "Somalia",
    "ZA": "Sudafrica",
    "GS": "Georgia del Sud e Isole Sandwich meridionali",
    "ES": "Spagna",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard e Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Svezia",
    "CH": "Svizzera",
    "SY": "Siria",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailandia",
    "TL": "Timor Est",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad e Tobago",
    "TN": "Tunisia",
    "TR": "Turchia",
    "TM": "Turkmenistan",
    "TC": "Isole Turks and Caicos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ucraina",
    "AE": "Emirati Arabi Uniti",
    "GB": "Regno Uniti",
    "US": "Stati Uniti d'America",
    "UM": "Stati Uniti Isole Minori",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Isole Vergini Britanniche",
    "VI": "Isole Vergini Statunitensi",
    "WF": "Wallis e Futuna",
    "EH": "Sahara Occidentale",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "AX": "Isole Åland",
    "BQ": "Caraibi Olandesi",
    "CW": "Curaçao",
    "GG": "Guernsey",
    "IM": "Isola di Man",
    "JE": "Baliato di Jersey",
    "ME": "Montenegro",
    "BL": "Saint-Barthélemy (Antille francesi)",
    "MF": "Sint Maarten (parte francese)",
    "RS": "Serbia",
    "SX": "Sint Maarten (parte olandese)",
    "SS": "Sudan del Sud"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
