var i18n = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "l'Algeria",
    "AS": "Samoa americane",
    "AD": "Andorra",
    "AO": "l'Angola",
    "AI": "Anguilla",
    "AQ": "Antartide",
    "AG": "Antigua e Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgio",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "il Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia-Erzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brasile",
    "IO": "Territorio britannico dell'Oceano Indiano",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "il Burundi",
    "KH": "Cambogia",
    "CM": "il Camerun",
    "CA": "Canada",
    "CV": "Capo Verde",
    "KY": "Isole Cayman",
    "CF": "Repubblica Centrafricana",
    "TD": "Chad",
    "CL": "Cile",
    "CN": "La Cina",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling)",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Repubblica Democratica del Congo",
    "CK": "Isole Cook",
    "CR": "Costa Rica",
    "CI": "Costa d'Avorio",
    "HR": "Croazia",
    "CU": "Cuba",
    "CY": "Cipro",
    "CZ": "Repubblica Ceca",
    "DK": "La Danimarca",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Repubblica Dominicana",
    "CE": "Ecuador",
    "EG": "Egitto",
    "SV": "El Salvador",
    "GQ": "Guinea Equatoriale",
    "ER": "L'Eritrea",
    "EE": "Estonia",
    "ET": "Etiopia",
    "FK": "Isole Falkland (Malvinas)",
    "FO": "Isole Faroe",
    "FJ": "Fiji",
    "FI": "Finlandia",
    "FR": "La Francia",
    "GF": "Guyana Francese",
    "PF": "Polinesia Francese",
    "TF": "Territori francesi meridionali",
    "GA": "Il Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germania",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Grecia",
    "GL": "Greenland",
    "GD": "Granada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "la Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guiana",
    "HT": "Haiti",
    "HM": "Isole Heard e McDonald",
    "VA": "Santa Sede (Cittì del Vaticano)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Ungheria",
    "IS": "Islanda",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Repubblica islamica dell'Iran",
    "IQ": "l'Iraq",
    "IE": "Irlanda",
    "IL": "Israele",
    "IT": "L'Italia",
    "JM": "Jamaica",
    "JP": "Il Giappone",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Il Kenya",
    "KI": "Kiribati",
    "KP": "Repubblica Popolare Democratica di Corea",
    "KR": "Repubblica di Corea",
    "KW": "il Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Repubblica democratica popolare del Laos",
    "LV": "la Lettonia",
    "LB": "Il Libano",
    "LS": "Lesoto",
    "LR": "Liberia",
    "LY": "Jamahiriya araba libica",
    "LI": "Liechtenstein",
    "LT": "Lituania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "L'ex Repubblica iugoslava di Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malesia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Isole Marshall",
    "MQ": "Martinique",
    "MR": "La Mauritania",
    "MU": "Maurizio",
    "YT": "Mayotte",
    "MX": "Il Messico",
    "FM": "Stati federati di Micronesia",
    "MD": "Repubblica di Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Marocco",
    "MZ": "Il Mozambico",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Olanda",
    "NC": "Nuova Caledonia",
    "NZ": "New Zealand",
    "NI": "Il Nicaragua",
    "NE": "Il Niger",
    "NG": "La Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Isole Marianne Settentrionali",
    "NO": "Norvegia",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Territori palestinesi occupati",
    "PA": "Panama",
    "PG": "Papua Nuova Guinea",
    "PY": "Paraguay",
    "PE": "Perø",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Polonia",
    "PT": "Portogallo",
    "PR": "Porto Rico",
    "QA": "Il Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Federazione Russa",
    "RW": "Rwanda",
    "SH": "Sant'Elena",
    "KN": "Saint Christopher e Nevis",
    "LC": "Santa Lucia",
    "PM": "Saint Pierre e Miquelon",
    "VC": "Saint Vincent e Grenadine",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome e Principe",
    "SA": "Arabia Saudita",
    "SN": "Senegal",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovacchia",
    "SI": "La Slovenia",
    "SB": "Isole Salomone",
    "SO": "La Somalia",
    "ZA": "Sud Africa",
    "GS": "Georgia del Sud e isole Sandwich del Sud",
    "ES": "Spagna",
    "LK": "Sri Lanka",
    "SD": "Il Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard e Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Svezia",
    "CH": "Svizzera",
    "SY": "Siria",
    "TW": "Taiwan, Provincia della Cina",
    "TJ": "Tajikistan",
    "TZ": "Repubblica Unita di Tanzania",
    "TH": "Thailand",
    "TL": "Timor Est",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad e Tobago",
    "TN": "La Tunisia",
    "TR": "La Turchia",
    "TM": "il Turkmenistan",
    "TC": "Turks e Caicos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "l'Ucraina",
    "AE": "Emirati Arabi Uniti",
    "GB": "Regno Unito",
    "US": "Stati Uniti",
    "UM": "Stati Uniti Isole Minori",
    "UY": "Uruguay",
    "UZ": "l'Uzbekistan",
    "VU": "Vanuatu",
    "VE": "il Venezuela",
    "VN": "Vietnam",
    "VG": "Isole Vergini Britanniche",
    "VI": "Virgin Islands, Stati Uniti",
    "WF": "Wallis e Futuna",
    "EH": "Sahara Occidentale",
    "YE": "Lo Yemen",
    "ZM": "lo Zambia",
    "ZW": "lo Zimbabwe",
    "AX": "Isole ¯land",
    "BQ": "Caraibi Olandesi",
    "CW": "Curañao",
    "GG": "Di Guernsey",
    "IM": "Isola di Man",
    "JE": "Jersey",
    "ME": "Montenegro",
    "BL": "Saint BarthØlemy",
    "MF": "Saint Martin (parte francese)",
    "RS": "Serbia",
    "SX": "Sint Maarten (parte olandese)",
    "SS": "Sud Sudan"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
