var i18n = {
    "AF": "Afganistanas",
    "AL": "Albanija",
    "DZ": "Alžyras",
    "AS": "Amerikos Samoa",
    "AD": "Andora",
    "AO": "Angola",
    "AI": "Angilija",
    "AQ": "Antarktida",
    "AG": "Antigva ir Barbuda",
    "AR": "Argentina",
    "AM": "Armėnija",
    "AW": "Aruba",
    "AU": "Australija",
    "AT": "Austrija",
    "AZ": "Azerbaidžanas",
    "BS": "Bahamos",
    "BH": "Bahreinas",
    "BD": "Bangladešas",
    "BB": "Barbadosas",
    "BY": "Baltarusija",
    "BE": "Belgija",
    "BZ": "Belizas",
    "BJ": "Beninas",
    "BM": "Bermudų salos",
    "BT": "Butanas",
    "BO": "Bolivija",
    "BA": "Bosnija ir Hercegovina",
    "BW": "Botsvana",
    "BV": "Buvė",
    "BR": "Brazilija",
    "IO": "Indijos Vandenyno Britų Sritis",
    "BN": "Brunėjus",
    "BG": "Bulgarija",
    "BF": "Burkina Fasas",
    "BI": "Burundis",
    "KH": "Kambodža",
    "CM": "Kamerūnas",
    "CA": "Kanada",
    "CV": "Žaliasis Kyšulys",
    "KY": "Kaimanų salos",
    "CF": "Centrinės Afrikos Respublika",
    "TD": "Čadas",
    "CL": "Čilė",
    "CN": "Kinija",
    "CX": "Kalėdų sala",
    "CC": "Kokosų salos",
    "CO": "Kolumbija",
    "KM": "Komorai",
    "CG": "Kongo",
    "CD": "Kongo Demokratinė Respublika",
    "CK": "Kuko salas",
    "CR": "Kosta Rika",
    "CI": "Dramblio Kaulo Krantas",
    "HR": "Kroatija",
    "CU": "Kuba",
    "CY": "Kipras",
    "CZ": "Čekija",
    "DK": "Danija",
    "DJ": "Džibutis",
    "DM": "Dominika",
    "DO": "Dominikos Respublika",
    "EC": "Ekvadoras",
    "EG": "Egiptas",
    "SV": "Salvadoras",
    "GQ": "Pusiaujo Gvinėja",
    "ER": "Eritrėja",
    "EE": "Estija",
    "ET": "Etiopija",
    "FK": "Folklando (Malvinų) Salos",
    "FO": "Farerai",
    "FJ": "Fidžis",
    "FI": "Suomija",
    "FR": "Prancūzija",
    "GF": "Prancūzijos Gviana",
    "PF": "Prancūzijos Polinezija",
    "TF": "Prancūzijos Pietų Sritys",
    "GA": "Gabonas",
    "GM": "Gambija",
    "GE": "Gruzija",
    "DE": "Vokietija",
    "GH": "Gana",
    "GI": "Gibraltaras",
    "GR": "Graikija",
    "GL": "Grenlandija",
    "GD": "Grenada",
    "GP": "Gvadelupa",
    "GU": "Guamas",
    "GT": "Gvatemala",
    "GN": "Gvinėja",
    "GW": "Bisau Gvinėja",
    "GY": "Gajana",
    "HT": "Haitis",
    "HM": "Herdas ir Makdonaldas",
    "VA": "Vatikano",
    "HN": "Hondūras",
    "HK": "Honkongas",
    "HU": "Vengrija",
    "IS": "Islandija",
    "IN": "Indija",
    "ID": "Indonezija",
    "IR": "Iranas",
    "IQ": "Irakas",
    "IE": "Airija",
    "IL": "Izraelis",
    "IT": "Italija",
    "JM": "Jamaika",
    "JP": "Japonija",
    "JO": "Jordanija",
    "KZ": "Kazachstanas",
    "KE": "Kenija",
    "KI": "Kiribatis",
    "KP": "Šiaurės Korėja",
    "KR": "Pietų Korėja",
    "KW": "Kuveitas",
    "KG": "Kirgizija",
    "LA": "Laosas",
    "LV": "Latvija",
    "LB": "Libanas",
    "LS": "Lesotas",
    "LR": "Liberija",
    "LY": "Libija",
    "LI": "Lichtenšteinas",
    "LT": "Lietuva",
    "LU": "Liuksemburgas",
    "MO": "Makao",
    "MK": "Makedonija",
    "MG": "Madagaskaras",
    "MW": "Malavis",
    "MY": "Malaizija",
    "MV": "Maldyvai",
    "ML": "Malis",
    "MT": "Malta",
    "MH": "Maršalo salos ",
    "MQ": "Martinika",
    "MR": "Mauritanija",
    "MU": "Mauricijus",
    "YT": "Majota",
    "MX": "Meksika",
    "FM": "Mikronezija",
    "MD": "Moldavija",
    "MC": "Monakas",
    "MN": "Mongolija",
    "MS": "Montseratas",
    "MA": "Marokas",
    "MZ": "Mozambikas",
    "MM": "Mianmaras",
    "NA": "Namibija",
    "NR": "Nauru",
    "NP": "Nepalas",
    "NL": "Nyderlandai",
    "NC": "Naujoji Kaledonija",
    "NZ": "Naujoji Zelandija",
    "NI": "Nikaragva",
    "NE": "Nigeris",
    "NG": "Nigerija",
    "NU": "Niue",
    "NF": "Norfolk",
    "MP": "Marianų salos",
    "NO": "Norvegija",
    "OM": "Omanas",
    "PK": "Pakistanas",
    "PW": "Palau",
    "PS": "Palestina",
    "PA": "Panama",
    "PG": "Papua Naujoji Gvinėja",
    "PY": "Paragvajus",
    "PE": "Peru",
    "PH": "Filipinai",
    "PN": "Pitkernas",
    "PL": "Lenkija",
    "PT": "Portugalija",
    "PR": "Puerto Rikas",
    "QA": "Katara",
    "RE": "Reunjonas",
    "RO": "Rumunija",
    "RU": "Rusija",
    "RW": "Ruanda",
    "SH": "Elenos sala",
    "KN": "Sent Kitsas ir Nevis",
    "LC": "Sent Lusija ",
    "PM": "Sent Pjeras ir Mikelonas",
    "VC": "Sent Vinsentas ir Grenadinai",
    "WS": "Samoa",
    "SM": "San Marinas",
    "ST": "San Tomė ir Prinsipė ",
    "SA": "Saudo Arabija",
    "SN": "Senegalas",
    "SC": "Seišeliai ",
    "SL": "Siera Leonė",
    "SG": "Singapūras",
    "SK": "Slovakija",
    "SI": "Slovėnija",
    "SB": "Saliamono salos",
    "SO": "Somalis",
    "ZA": "Pietų Afrikos Respublika",
    "GS": "Pietų Džordžija ir Pietų Sandvičo salos",
    "ES": "Ispanija ",
    "LK": "Šri Lanka",
    "SD": "Sudanas",
    "SR": "Surinamas",
    "SJ": "Jan Majenas",
    "SZ": "Svazilandas",
    "SE": "Švedija",
    "CH": "Šveicarija",
    "SY": "Sirija",
    "TW": "Taivanas",
    "TJ": "Tadžikija",
    "TZ": "Tanzanija",
    "TH": "Tailandas",
    "TL": "Rytų Timoras",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidadas ir TobagasTunisas",
    "TN": "Tunisas",
    "TR": "Turkija",
    "TM": "Turkmėnija",
    "TC": "Terkso ir Kaikoso salos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraina",
    "AE": "Jungtiniai Arabų Emyratai",
    "GB": "Jungtinė Karalystė",
    "US": "JAV",
    "UM": "Mažosios aplinkinės salos",
    "UY": "Urugvajus",
    "UZ": "Uzbekija",
    "VU": "Vanuatu",
    "VE": "Venesuela",
    "VN": "Vietnamas",
    "VG": "Britu Virdžīnas",
    "VI": "JAV Mergelių salos ",
    "WF": "Volis ir Futūna",
    "EH": "Vakarų Sachara",
    "YE": "Jemenas",
    "ZM": "Zambija ",
    "ZW": "Zimbabvė",
    "AX": "Alandų salos",
    "BQ": "Olandų Karibų",
    "CW": "Curaçao",
    "GG": "Gernsio",
    "IM": "Menas Sala",
    "JE": "Džērsija",
    "ME": "Juodkalnija",
    "BL": "Gustavija",
    "MF": "Sint Martenas (Prancūzijos dalis)",
    "RS": "Serbija",
    "SX": "Sint Martenas (Nyderlandų dalis)",
    "SS": "Sudanas"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
