var i18n = {
    "AF": "Afganistāna",
    "AL": "Albānija",
    "DZ": "Alžīrija",
    "AS": "Samoa",
    "AD": "Andora",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarktika",
    "AG": "Antigva un Barbuda",
    "AR": "Argentīna",
    "AM": "Armēnija ",
    "AW": "Aruba",
    "AU": "Austrālija",
    "AT": "Austrija",
    "AZ": "Azerbaidžāna",
    "BS": "Bahamas",
    "BH": "Bahreina",
    "BD": "Bangladeša",
    "BB": "Barbadosa",
    "BY": "Baltkrievija",
    "BE": "Beļģija",
    "BZ": "Beliza",
    "BJ": "Benina",
    "BM": "Bermudu salas",
    "BT": "Butāna",
    "BO": "Bolīvija",
    "BA": "Bosnija un Hercegovina",
    "BW": "Botsvāna",
    "BV": "Buvē sala",
    "BR": "Brazīlija",
    "IO": "Britu Indijas okeāna teritorija",
    "BN": "Bruneja",
    "BG": "Bulgārija",
    "BF": "Burkinafaso",
    "BI": "Burundija",
    "KH": "Kambodža",
    "CM": "Kamerūna",
    "CA": "Kanāda",
    "CV": "Kaboverde",
    "KY": "Kaimanu salas",
    "CF": "Centrālāfrikas Republika",
    "TD": "Čada",
    "CL": "Čīle",
    "CN": "Ķīna",
    "CX": "Ziemsvētku sala",
    "CC": "Kokosu (Kīlinga) salas",
    "CO": "Kolumbija",
    "KM": "Komoru salas",
    "CG": "Kongo",
    "CD": "Kongo Demokrātiskā Republika",
    "CK": "Kuka salas",
    "CR": "Kostarika",
    "CI": "Kotdivuāra",
    "HR": "Horvātija",
    "CU": "Kuba",
    "CY": "Kipra",
    "CZ": "Čehija",
    "DK": "Dānija",
    "DJ": "Džibutija",
    "DM": "Dominika",
    "DO": "Dominikānas Republika",
    "EC": "Ekvadora",
    "EG": "Ēģipte",
    "SV": "Salvadora",
    "GQ": "Ekvatoriālā Gvineja ",
    "ER": "Eritreja",
    "EE": "Igaunija",
    "ET": "Etiopija",
    "FK": "Folklenda salas",
    "FO": "Fēru salas",
    "FJ": "Fidži",
    "FI": "Somija",
    "FR": "Francija",
    "GF": "Francijas Gviāna",
    "PF": "Francijas Polinēzija",
    "TF": "Francijas Dienvidjūru teritorija",
    "GA": "Gabona",
    "GM": "Gambija",
    "GE": "Gruzija",
    "DE": "Vācija",
    "GH": "Gana",
    "GI": "Gibraltārs",
    "GR": "Grieķija",
    "GL": "Grenlande",
    "GD": "Grenāda",
    "GP": "Gvadelupa",
    "GU": "Guama",
    "GT": "Gvatemala",
    "GN": "Gvineja",
    "GW": "Gvineja-Bisava",
    "GY": "Gajāna",
    "HT": "Haiti",
    "HM": "Hērda un Makdonalda salas",
    "VA": "Svētais Krēsls (Vatikāns)",
    "HN": "Hondurasa",
    "HK": "Hongkonga",
    "HU": "Ungārija",
    "IS": "Islande",
    "IN": "Indija",
    "ID": "Indonēzija",
    "IR": "Irāna",
    "IQ": "Irāka",
    "IE": "Īrija",
    "IL": "Izraēla",
    "IT": "Itālija",
    "JM": "Jamaika",
    "JP": "Japāna",
    "JO": "Jordānija",
    "KZ": "Kazahstāna",
    "KE": "Kenija",
    "KI": "Kiribati",
    "KP": "Korejas Tautas Demokrātiskā Republika",
    "KR": "Korejas Republika",
    "KW": "Kuveita",
    "KG": "Kirgizstāna",
    "LA": "Laosa",
    "LV": "Latvija",
    "LB": "Libāna",
    "LS": "Lesoto",
    "LR": "Libērija",
    "LY": "Lībija",
    "LI": "Lihtenšteina",
    "LT": "Lietuva",
    "LU": "Luksemburga",
    "MO": "Makao",
    "MK": "Maķedonija",
    "MG": "Madagaskara",
    "MW": "Malāvija",
    "MY": "Malaizija",
    "MV": "Maldīvija",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Māršala salas",
    "MQ": "Martinika",
    "MR": "Mauritānija",
    "MU": "Maurīcija",
    "YT": "Majota",
    "MX": "Meksika",
    "FM": "Mikronēzija",
    "MD": "Moldova",
    "MC": "Monako",
    "MN": "Mongolija",
    "MS": "Montserrata",
    "MA": "Maroka",
    "MZ": "Mozambika",
    "MM": "Mjanma",
    "NA": "Namībija",
    "NR": "Nauru",
    "NP": "Nepāla",
    "NL": "Nīderlande",
    "NC": "Jaunkaledonija ",
    "NZ": "Jaunzēlande",
    "NI": "Nikaragva",
    "NE": "Nigēra",
    "NG": "Nigērija",
    "NU": "Niue",
    "NF": "Norfolka",
    "MP": "Ziemeļu Marianas",
    "NO": "Norvēģija",
    "OM": "Omāna",
    "PK": "Pakistāna",
    "PW": "Palau",
    "PS": "Okupētā Palestīnas teritorija",
    "PA": "Panama",
    "PG": "Papua-Jaungvineja",
    "PY": "Paragvaja",
    "PE": "Peru",
    "PH": "Filipīnas",
    "PN": "Pitkērna",
    "PL": "Polija",
    "PT": "Portugāle",
    "PR": "Puertoriko",
    "QA": "Katara",
    "RE": "Reinjona",
    "RO": "Romānija",
    "RU": "Krievija",
    "RW": "Ruanda",
    "SH": "Svētās Helēnassala",
    "KN": "Sentkitsa un Nevisa ",
    "LC": "Sentlūsija",
    "PM": "Senpjēra un Mikelona",
    "VC": "Sentvinsenta un Grenadīnas",
    "WS": "Rietumsamoa",
    "SM": "Sanmarīno",
    "ST": "Santome un Prinsipi",
    "SA": "Saūda Arābija",
    "SN": "Senegāla",
    "SC": "Seišeļu salas",
    "SL": "Sjerraleone",
    "SG": "Singapūra",
    "SK": "Slovākija",
    "SI": "Slovēnija",
    "SB": "Zālamana salas",
    "SO": "Somālija",
    "ZA": "Dienvidāfrika ",
    "GS": "Dienviddžordžija un Dienvidsendviču salas",
    "ES": "Spānija",
    "LK": "Šrilanka",
    "SD": "Sudāna",
    "SR": "Surinama",
    "SJ": "Svalbāra un JanaMajena sala",
    "SZ": "Svazilenda ",
    "SE": "Zviedrija ",
    "CH": "Šveice",
    "SY": "Sīrija",
    "TW": "Taivāna",
    "TJ": "Tadžikistāna",
    "TZ": "Tanzānija",
    "TH": "Taizeme",
    "TL": "Austrumtimor",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidāda un Tobāgo",
    "TN": "Tunisija",
    "TR": "Turcija",
    "TM": "Turkmenistāna",
    "TC": "Tērksas un Kaikosas",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraina",
    "AE": "Apvienotie Arābu Emirāti",
    "GB": "Lielbritānija",
    "US": "Amerikas Savienotās Valstis",
    "UM": "ASV mazās aizjūras teritorijas",
    "UY": "Urugvaja",
    "UZ": "Uzbekistāna",
    "VU": "Vanuatu",
    "VE": "Venezuēla",
    "VN": "Vietnama",
    "VG": "Britu Virdžīnas",
    "VI": "Amerikāņu Virdžīnas ",
    "WF": "Volisa un Futuna",
    "EH": "Rietumsahāra",
    "YE": "Jemena",
    "ZM": "Zambija",
    "ZW": "Zimbabve",
    "AX": "Ālandu salas",
    "BQ": "Dutch Caribbean",
    "CW": "Curaçao",
    "GG": "Guernsey",
    "IM": "Menas sala",
    "JE": "Džērsija",
    "ME": "Melnkalne",
    "BL": "Saint-Barthelemy (French West Indies)",
    "MF": "Sint Maarten (Francijas daļa)",
    "RS": "Serbija",
    "SX": "Sint Maarten (Nīderlandes daļa)",
    "SS": "Sudāna"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
