var i18n = {
	"AF": "Afghanistan",
	"AL": "Albanië",
	"DZ": "Algerije",
	"AS": "Amerikaans-Samoa",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarctica",
	"AG": "Antigua en Barbuda",
	"AR": "Argentinië",
	"AM": "Armenië",
	"AW": "Aruba",
	"AU": "Australië",
	"AT": "Österreich",
	"AZ": "Azerbeidzjan",
	"BS": "Bahama's",
	"BH": "Bahrain",
	"BD": "Bangladesh",
	"BB": "Barbados",
	"BY": "Belarus",
	"BE": "België",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BT": "Bhutan",
	"BO": "Bolivia",
	"BA": "Bosnië en Herzegovina",
	"BW": "Botswana",
	"BV": "Bouveteiland",
	"BR": "Brazilië",
	"IO": "Brits Territorium in de Indische Oceaan",
	"BN": "Brunei",
	"BG": "Bulgarije",
	"BF": "Burkina Faso",
	"BI": "Burundi",
	"KH": "Cambodja",
	"CM": "Kameroen",
	"CA": "Canada",
	"CV": "Kaapverdië",
	"KY": "Caymaneilanden",
	"CF": "Centraal-Afrikaanse Republiek",
	"TD": "Tsjaad",
	"CL": "Chili",
	"CN": "China",
	"CX": "Christmaseiland",
	"CC": "Cocoseilanden",
	"CO": "Colombia",
	"KM": "Comoren",
	"CG": "Congo",
	"CD": "Democratische Republiek Congo",
	"CK": "Cookeilanden",
	"CR": "Costa Rica",
	"CI": "Ivoorkust",
	"HR": "Kroatië",
	"CU": "Cuba",
	"CY": "Cyprus",
	"CZ": "Tsjechië",
	"DK": "Denemarken",
	"DJ": "Djibouti",
	"DM": "Dominica",
	"DO": "Dominicaanse Republiek",
	"EC": "Ecuador",
	"EG": "Egypte",
	"SV": "El Salvador",
	"GQ": "Equatoriaal-Guinea",
	"ER": "Eritrea",
	"EE": "Estland",
	"ET": "Ethiopië",
	"FK": "Falklandeilanden",
	"FO": "Faeröer",
	"FJ": "Fiji",
	"FI": "Finland",
	"FR": "Frankrijk",
	"GF": "Frans-Guyana",
	"PF": "Frans-Polynesië",
	"TF": "Franse Gebieden in de zuidelijke Indische Oceaan",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Georgië",
	"DE": "Duitsland",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GR": "Griekenland",
	"GL": "Groenland",
	"GD": "Grenada",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GN": "Guinee",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haïti",
	"HM": "Heard en McDonaldeilanden",
	"VA": "Vaticaanstad",
	"HN": "Honduras",
	"HK": "Hongkong",
	"HU": "Hongarije",
	"IS": "IJsland",
	"IN": "India",
	"ID": "Indonesië",
	"IR": "Iran",
	"IQ": "Irak",
	"IE": "Ierland",
	"IL": "Israël",
	"IT": "Italië",
	"JM": "Jamaica",
	"JP": "Japan",
	"JO": "Jordanië",
	"KZ": "Kazachstan",
	"KE": "Kenya",
	"KI": "Kiribati",
	"KP": "Noord-Korea",
	"KR": "Zuid-Korea",
	"KW": "Koeweit",
	"KG": "Kirgizstan",
	"LA": "Laos",
	"LV": "Letland",
	"LB": "Libanon",
	"LS": "Lesotho",
	"LR": "Liberia",
	"LY": "Libië",
	"LI": "Liechtenstein",
	"LT": "Litouwen",
	"LU": "Luxemburg",
	"MO": "Macau",
	"MK": "Voormalige Joegoslavische Republiek Macedonië",
	"MG": "Madagaskar",
	"MW": "Malawi",
	"MY": "Maleisië",
	"MV": "Maldiven",
	"ML": "Mali",
	"MT": "Malta",
	"MH": "Marshalleilanden",
	"MQ": "Martinique",
	"MR": "Mauritanië",
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Mexico",
	"FM": "Micronesia",
	"MD": "Moldavië",
	"MC": "Monaco",
	"MN": "Mongolië",
	"MS": "Montserrat",
	"MA": "Marokko",
	"MZ": "Mozambique",
	"MM": "Myanmar",
	"NA": "Namibië",
	"NR": "Nauru",
	"NP": "Nepal",
	"NL": "Nederland",
	"NC": "Nieuw-Caledonië",
	"NZ": "Nieuw-Zeeland",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"NU": "Niue",
	"NF": "Norfolkeiland",
	"MP": "Noordelijke Marianen",
	"NO": "Noorwegen",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PS": "Palestina (staat)",
	"PA": "Panama",
	"PG": "Papoea-Nieuw-Guinea",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Filipijnen",
	"PN": "Pitcairn (eiland)",
	"PL": "Polen",
	"PT": "Portugal",
	"PR": "Puerto Rico",
	"QA": "Qatar",
	"RE": "Réunion",
	"RO": "Roemenië",
	"RU": "Rusland",
	"RW": "Rwanda",
	"SH": "Sint-Helena",
	"KN": "Sint Kitts en Nevis",
	"LC": "Saint Lucia",
	"PM": "Saint-Pierre en Miquelon",
	"VC": "Saint Vincent en de Grenadines",
	"WS": "Samoa",
	"SM": "San Marino",
	"ST": "Sao Tomé en Principe",
	"SA": "Saoedi-Arabië",
	"SN": "Senegal",
	"SC": "Seychellen",
	"SL": "Sierra Leone",
	"SG": "Singapore",
	"SK": "Slovakije",
	"SI": "Slovenië",
	"SB": "Salomonseilanden",
	"SO": "Somalië",
	"ZA": "Zuid-Afrika",
	"GS": "Zuid-Georgië en Zuidelijke Sandwicheilanden",
	"ES": "Spanje",
	"LK": "Sri Lanka",
	"SD": "Sudan",
	"SR": "Suriname",
	"SJ": "	Svalbard en Jan Mayen",
	"SZ": "Swaziland",
	"SE": "Zweden",
	"CH": "Zwitserland",
	"SY": "Syrië",
	"TW": "Taiwan",
	"TJ": "Tadzjikistan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TL": "Timor-Leste",
	"TG": "Togo",
	"TK": "Tokelau-eilanden",
	"TO": "Tonga",
	"TT": "Trinidad en Tobago",
	"TN": "Tunesië",
	"TR": "Turkije",
	"TM": "Turkmenistan",
	"TC": "Turks- en Caicoseilanden",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Oekraïne",
	"AE": "Verenigde Arabische Emiraten",
	"GB": "Verenigd Koninkrijk",
	"US": "Verenigde Staten",
	"UM": "Amerikaanse ondergeschikte afgelegen eilanden",
	"UY": "Uruguay",
	"UZ": "Oezbekistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"VG": "Britse Maagdeneilanden",
	"VI": "Amerikaanse Maagdeneilanden",
	"WF": "Wallis en Futuna",
	"EH": "Westelijke Sahara",
	"YE": "Jemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
	"AX": "Åland",
	"BQ": "Caribisch Nederland",
	"CW": "Curaçao",
	"GG": "Guernsey",
	"IM": "Man (eiland)",
	"JE": "Jersey",
	"ME": "Montenegro",
	"BL": "Saint-Barthélemy (eiland)",
	"MF": "Sint Maarten (eiland)",
	"RS": "Servië",
	"SX": "Sint Maarten (land)",
	"SS": "Zuid-Soedan"
};

exports.i18n = function() {
	"use strict";
 	return i18n;
};
