var i18n = {
	"AF": "Afghanistan",
	"AL": "Albánsko",
	"DZ": "Alžírsko",
	"AS": "Americká Samoa",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarctica",
	"AG": "Antigua a Barbuda",
	"AR": "Argentína",
	"AM": "Arménsko",
	"AW": "Aruba",
	"AU": "Austrália",
	"AT": "Rakúsko",
	"AZ": "Azerbajdžan",
	"BS": "Bahamy",
	"BH": "Bahrajn",
	"BD": "Bangladéš",
	"BB": "Barbados",
	"BY": "Bielorusko",
	"BE": "Belgicko",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BT": "Bhután",
	"BO": "Bolivia",
	"BA": "Bosna a Hercegovina",
	"BW": "Botswana",
	"BV": "Bouvetov ostrov",
	"BR": "Brazília",
	"IO": "Britské indickooceánske územie",
	"BN": "Brunej",
	"BG": "Bulharsko",
	"BF": "Burkina",
	"BI": "Burundi",
	"KH": "Kambodža",
	"CM": "Kamerun",
	"CA": "Kanada",
	"CV": "Kapverdy",
	"KY": "Kajmanie ostrovy",
	"CF": "Stredoafrická republika",
	"TD": "Čad",
	"CL": "Čile",
	"CN": "Čína",
	"CX": "Vianočný ostrov",
	"CC": "Kokosové ostrovy (Keeling)",
	"CO": "Kolumbia",
	"KM": "Komory",
	"CG": "Kongo",
	"CD": "Konžská demokratická republika",
	"CK": "Cookove ostrovy",
	"CR": "Kostarika",
	"CI": "Pobrežie Slonoviny",
	"HR": "Chorvátsko",
	"CU": "Kuba",
	"CY": "Cyprus",
	"CZ": "Česko",
	"DK": "Dánsko",
	"DJ": "Džibuti",
	"DM": "Dominica",
	"DO": "Dominikánska republika",
	"EC": "Ekvádor",
	"EG": "Egypt",
	"SV": "Salvádor",
	"GQ": "Rovníková Guinea",
	"ER": "Eritrea",
	"EE": "Estónsko",
	"ET": "Etiópia ",
	"FK": "Falklandy (Malvinas)",
	"FO": "Faerské ostrovy",
	"FJ": "Fidži ",
	"FI": "Fínsko",
	"FR": "Francúzsko",
	"GF": "Francúzsky Guyana",
	"PF": "Francúzska Polynézia",
	"TF": "Francúzske južné a antarktické územia",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Gruzínsko",
	"DE": "Nemecko",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GR": "Grécko",
	"GL": "Grónsko",
	"GD": "Grenada",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haiti",
	"HM": "Heardov ostrov",
	"VA": "Vatikán",
	"HN": "Honduras",
	"HK": "Hong Kong",
	"HU": "Maďarsko",
	"IS": "Island",
	"IN": "India",
	"ID": "Indonézia",
	"IR": "Irán",
	"IQ": "Irak",
	"IE": "Írsko",
	"IL": "Izrael",
	"IT": "Taliansko",
	"JM": "Jamajka",
	"JP": "Japonsko",
	"JO": "Jordán",
	"KZ": "Kazachstan",
	"KE": "Keňa",
	"KI": "Kiribati",
	"KP": "Severná Kórea",
	"KR": "Jižní Korea",
	"KW": "Kuvajt",
	"KG": "Kirgizsko",
	"LA": "Laos",
	"LV": "Lotyšsko",
	"LB": "Libanon",
	"LS": "Lesotho",
	"LR": "Libéria",
	"LY": "Líbya",
	"LI": "Lichtenštajnsko",
	"LT": "Litva",
	"LU": "Luxembursko",
	"MO": "Macao",
	"MK": "Macedónsko",
	"MG": "Madagaskar",
	"MW": "Malawi",
	"MY": "Malajzia",
	"MV": "Maldivy",
	"ML": "Mali",
	"MT": "Malta",
	"MH": "Marshallove ostrovy",
	"MQ": "Martinik",
	"MR": "Mauritániou",
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Mexiko",
	"FM": "Mikronézia ",
	"MD": "Moldavsko",
	"MC": "Monako",
	"MN": "Mongolsko",
	"MS": "Montserrat",
	"MA": "Maroko",
	"MZ": "Mozambik",
	"MM": "Mjanmarsko",
	"NA": "Namíbia",
	"NR": "Nauru",
	"NP": "Nepál",
	"NL": "Holandsko",
	"NC": "Nová Kaledónia",
	"NZ": "Nový Zéland",
	"NI": "Nikaragua",
	"NE": "Niger",
	"NG": "Nigéria",
	"NU": "Niue",
	"NF": "Ostrov Norfolk",
	"MP": "Severné Mariány",
	"NO": "Nórsko",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PS": "Palestína",
	"PA": "Panama",
	"PG": "Papua-Nová Guinea",
	"PY": "Paraguaj",
	"PE": "Peru",
	"PH": "Filipíny",
	"PN": "Pitcairn",
	"PL": "Poľsko",
	"PT": "Portugalsko",
	"PR": "Portoriko",
	"QA": "Katar",
	"RE": "Réunion",
	"RO": "Rumunsko",
	"RU": "Rusko ",
	"RW": "Rwanda",
	"SH": "Svätá Helena",
	"KN": "Svätý Krištof a Nevis",
	"LC": "Svätá Lucia",
	"PM": "Ostrovy Saint Pierre a Miquelon",
	"VC": "Svätý Vincent a Grenadíny",
	"WS": "Samoa",
	"SM": "San Maríno",
	"ST": "Svätý Tomáš a Princov ostrov",
	"SA": "Saudská Arábia",
	"SN": "Senegal",
	"SC": "Seychely",
	"SL": "Sierra Leone",
	"SG": "Singapore",
	"SK": "Slovakia",
	"SI": "Slovinsko",
	"SB": "Šalamúnove ostrovy",
	"SO": "Somálsko",
	"ZA": "Južná Afrika",
	"GS": "Južná Georgia a Južné Sandwichove ostrovy",
	"ES": "Španielsko",
	"LK": "Srí Lanka",
	"SD": "Sudán",
	"SR": "Surinam",
	"SJ": "Svalbard a Jan Mayen",
	"SZ": "Svazijsko",
	"SE": "Švédsko",
	"CH": "Švajčiarsko",
	"SY": "Sýria",
	"TW": "Taiwan",
	"TJ": "Tadžikistan",
	"TZ": "Tanzánia",
	"TH": "Thajsko",
	"TL": "Východný Timor",
	"TG": "Togo",
	"TK": "Tokelau",
	"TO": "Tonga",
	"TT": "Trinidad a Tobago",
	"TN": "Tunisko",
	"TR": "Turecko",
	"TM": "Turkménsko",
	"TC": "Turks a Caicos",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Ukrajina",
	"AE": "Spojené arabské emiráty",
	"GB": "Spojené kráľovstvo",
	"US": "Spojené štáty",
	"UM": "Menšie odľahlé ostrovy USA",
	"UY": "Uruguaj",
	"UZ": "Uzbekistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"VG": "Britské Panenské ostrovy",
	"VI": "Americké Panenské ostrovy",
	"WF": "Wallis a Futuna",
	"EH": "Západná Sahara",
	"YE": "Jemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
	"AX": "Alandy",
	"BQ": "Karipska Holandsko",
	"CW": "Curaçao",
	"GG": "Guernsey",
	"IM": "Ostrov Man",
	"JE": "Jersey",
	"ME": "Čierna Hora",
	"BL": "Svätý Bartolomej (ostrov)",
	"MF": "Svätý Martin (ostrov)",
	"RS": "Srbsko",
	"SX": "Sint Maarten",
	"SS": "Južný Sudán"
};

exports.i18n = function() {
	"use strict";
	return i18n;
};
