var i18n = {
    "AF": "Afganistan",
    "AL": "Albanija",
    "DZ": "Alžirija",
    "AS": "Samoa",
    "AD": "Andora",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarktika",
    "AG": "Antigva in Barbuda",
    "AR": "Argentina",
    "AM": "Armenija",
    "AW": "Aruba",
    "AU": "Avstralija",
    "AT": "Avstrija",
    "AZ": "Azerbajdžan",
    "BS": "Bahami",
    "BH": "Bahrain",
    "BD": "Bangladeš",
    "BB": "Barbados",
    "BY": "Belorusija",
    "BE": "Belgija",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermudi",
    "BT": "Butan",
    "BO": "Bolivija",
    "BA": "Bosna in Hercegovina",
    "BW": "Bocvana",
    "BV": "Bouvetov otok",
    "BR": "Brazil",
    "IO": "Britansko ozemlje v Indijskem oceanu",
    "BN": "Brunej",
    "BG": "Bolgarija",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Kambodža",
    "CM": "Kamerun",
    "CA": "Kanada",
    "CV": "Zelenortski otoki",
    "KY": "Kajmanji otoki",
    "CF": "Srednjeafriška republika",
    "TD": "Čad",
    "CL": "Čile",
    "CN": "Kina",
    "CX": "Kiritimati",
    "CC": "Kokosovi otoki",
    "CO": "Kolombija",
    "KM": "Komori",
    "CG": "Kongo",
    "CD": "Demokratična republika Kongo",
    "CK": "Cookovi otoki",
    "CR": "Costarika",
    "CI": "Slonokoščena obala",
    "HR": "Hrvaška",
    "CU": "Kuba",
    "CY": "Ciper",
    "CZ": "Češka Republika",
    "DK": "Danska",
    "DJ": "Džibuti",
    "DM": "Dominika",
    "DO": "Dominikanska republika",
    "EC": "Ekvador",
    "EG": "Egipt",
    "SV": "Salvador",
    "GQ": "Gvineja",
    "ER": "Eritreja",
    "EE": "Estonija",
    "ET": "Etiopija",
    "FK": "Falklandski otoki",
    "FO": "Ferski otoki",
    "FJ": "Fidži",
    "FI": "Finska",
    "FR": "Francija",
    "GF": "Gvajana",
    "PF": "Francoska Polinezija",
    "TF": "Francoska južna in antarktična ozemlja",
    "GA": "Gabon",
    "GM": "Gambija",
    "GE": "Georgia",
    "DE": "Nemčija",
    "GH": "Gana",
    "GI": "Gibraltar",
    "GR": "Grčija",
    "GL": "Grenlandija",
    "GD": "Grenada",
    "GP": "Gvadelup",
    "GU": "Guam",
    "GT": "Gvatemala",
    "GN": "Gvineja",
    "GW": "Gvineja Bissau",
    "GY": "Gvajana",
    "HT": "Haiti",
    "HM": "Otok Heard in otočje McDonald",
    "VA": "Vatikan",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Madžarska",
    "IS": "Islandija",
    "IN": "Indija",
    "ID": "Indonesija",
    "IR": "Islamska republika Iran",
    "IQ": "Irak",
    "IE": "Irska",
    "IL": "Izrael",
    "IT": "Italija",
    "JM": "Jamajka",
    "JP": "Japonska",
    "JO": "Jordanija",
    "KZ": "Kazakhstan",
    "KE": "Kenija",
    "KI": "Kiribati",
    "KP": "Severna Koreja",
    "KR": "Južna Koreja",
    "KW": "Kuvait",
    "KG": "Kirgizistan",
    "LA": "Laos",
    "LV": "Latvija",
    "LB": "Libanon",
    "LS": "Lesoto",
    "LR": "Liberija",
    "LY": "Libija",
    "LI": "Lihtenštajn",
    "LT": "Litva",
    "LU": "Luksemburg",
    "MO": "Macau",
    "MK": "Republika Makedonija",
    "MG": "Madagaskar",
    "MW": "Malavi",
    "MY": "Malesija",
    "MV": "Maldivi",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshallovi otoki",
    "MQ": "Martinik",
    "MR": "Mavretanija",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mehika",
    "FM": "Združene države Mikronezije",
    "MD": "Moldavija",
    "MC": "Monako",
    "MN": "Mongolija",
    "MS": "Monserrat",
    "MA": "Maroko",
    "MZ": "Mozambik",
    "MM": "Mjanmar",
    "NA": "Namibija",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Nizozemska",
    "NC": "Nova Kaledonija",
    "NZ": "Nova Zelandija",
    "NI": "Nikaragva",
    "NE": "Niger",
    "NG": "Nigerija",
    "NU": "Niue",
    "NF": "Norfolk",
    "MP": "Severni Marianski otoki",
    "NO": "Norveška",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestina",
    "PA": "Panama",
    "PG": "Papua Nova Gvineja",
    "PY": "Paragvaj",
    "PE": "Peru",
    "PH": "Filipini",
    "PN": "Pitcairnovi otoki",
    "PL": "Poljska",
    "PT": "Portugalska",
    "PR": "Porto Rico",
    "QA": "Katar",
    "RE": "Reunion",
    "RO": "Romunija",
    "RU": "Rusija",
    "RW": "Ruanda",
    "SH": "Saint Elena",
    "KN": "Sveti Krištof in Nevis",
    "LC": "Saint Lucia",
    "PM": "Saint Pierre e Miquelon",
    "VC": "Saint Vincent e Grenadine",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome in Principe",
    "SA": "Saudova Arabija",
    "SN": "Senegal",
    "SC": "Sejšeli",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovaška",
    "SI": "Slovenija",
    "SB": "Solomon",
    "SO": "Somalija",
    "ZA": "Južna Afrika",
    "GS": "Južna Georgia in otoki Južni Sandwich",
    "ES": "Španija",
    "LK": "Šri Lanka",
    "SD": "Sudan",
    "SR": "Surinam",
    "SJ": "Svalbard in Jan Mayen",
    "SZ": "Svazi",
    "SE": "Švedska",
    "CH": "Švica",
    "SY": "Sirija",
    "TW": "Tajvan",
    "TJ": "Tadžikistan",
    "TZ": "Tanzanija",
    "TH": "Tajska",
    "TL": "Timor Est",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad in Tobago",
    "TN": "Tunizija",
    "TR": "Turčija",
    "TM": "Turkmenistan",
    "TC": "Isole Turks and Caicos",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukrajina",
    "AE": "Združeni arabski emirati",
    "GB": "Združeno kraljestvo",
    "US": "Združene države Amerike",
    "UM": "Stranski zunanji otoki Združenih držav ",
    "UY": "Urugvaj",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Britanski Deviški otoki",
    "VI": "Deviški otoki Združenih držav",
    "WF": "Wallis in Futuna",
    "EH": "Zahodna Sahara",
    "YE": "Jemen",
    "ZM": "Zambija",
    "ZW": "Zimbabve",
    "AX": "Isole Åland",
    "BQ": "Nizozemski Karibi",
    "CW": "Curaçao",
    "GG": "Guernsey",
    "IM": "Man",
    "JE": "Jersey",
    "ME": "Črna gora",
    "BL": "Saint-Barthelemy (Francoska Zahodna Indija)",
    "MF": "Sint Maarten (francoski del)",
    "RS": "Srbija",
    "SX": "Sint Maarten (nizozemski del)",
    "SS": "Sudan"
};

exports.i18n = function () {
    "use strict";
    return i18n;
};
