var i18n = {
	"AF": "Afghanistan",
	"AL": "Albanien",
	"DZ": "Algeriet",
	"AS": "Amerikanska Samoa",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarktis",
	"AG": "Antigua och Barbuda",
	"AR": "Argentina",
	"AM": "Armenien",
	"AW": "Aruba",
	"AU": "Australien",
	"AT": "Österrike",
	"AZ": "Azerbajdzjan",
	"BS": "Bahamas",
	"BH": "Bahrain",
	"BD": "Bangladesh",
	"BB": "Barbados",
	"BY": "Vitryssland",
	"BE": "Belgien",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BT": "Bhutan",
	"BO": "Bolivia",
	"BA": "Bosnien och Hercegovina",
	"BW": "Botswana",
	"BV": "Bouvetön",
	"BR": "Brasilien",
	"IO": "Brittiska territoriet i Indiska oceanen",
	"BN": "Brunei",
	"BG": "Bulgarien",
	"BF": "Burkina Faso",
	"BI": "Burundi",
	"KH": "Kambodja",
	"CM": "Kamerun",
	"CA": "Kanada",
	"CV": "Kap Verde",
	"KY": "Îles Caïmans",
	"CF": "Centralafrikanska republiken",
	"TD": "Tchad",
	"CL": "Chile",
	"CN": "Kina",
	"CX": "Julön",
	"CC": "Kokosöarna",
	"CO": "Colombia",
	"KM": "Komorerna",
	"CG": "Kongo",
	"CD": "Demokratiska republiken Kongo",
	"CK": "Cooköarna",
	"CR": "Costa Rica",
	"CI": "Elfenbenskusten",
	"HR": "Kroatien",
	"CU": "Kuba",
	"CY": "Cypern",
	"CZ": "Tjeckien",
	"DK": "Danmark",
	"DJ": "Djibouti",
	"DM": "Dominica",
	"DO": "Dominikanska republiken",
	"EC": "Ecuador",
	"EG": "Egypten",
	"SV": "El Salvador",
	"GQ": "Ekvatorialguinea",
	"ER": "Eritrea",
	"EE": "Estland",
	"ET": "Etiopien",
	"FK": "Falklandsöarna ",
	"FO": "Färöarna",
	"FJ": "Fiji",
	"FI": "Finland",
	"FR": "Frankrike",
	"GF": "Franska Guyana",
	"PF": "Franska Polynesien",
	"TF": "Franska Sydterritorierna",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Georgien",
	"DE": "Tyskland",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GR": "Grekland ",
	"GL": "Grönland",
	"GD": "Grenada",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haiti",
	"HM": "Hört och Mcdonaldsöarna",
	"VA": "Heliga stolen ",
	"HN": "Honduras",
	"HK": "Hongkong",
	"HU": "Ungern",
	"IS": "Island",
	"IN": "Indien",
	"ID": "Indonesien",
	"IR": "Iran",
	"IQ": "Irak",
	"IE": "Irland",
	"IL": "Israel",
	"IT": "Italien",
	"JM": "Jamaica",
	"JP": "Japan",
	"JO": "Jordan",
	"KZ": "Kazakstan",
	"KE": "Kenya",
	"KI": "Kiribati",
	"KP": "Nordkorea",
	"KR": "Sydkorea",
	"KW": "Kuwait",
	"KG": "Kirgizistan",
	"LA": "Laos",
	"LV": "Lett",
	"LB": "Libanon",
	"LS": "Lesotho",
	"LR": "Liberia",
	"LY": "Libyen",
	"LI": "Liechtenstein",
	"LT": "Litauen",
	"LU": "Luxemburg",
	"MO": "Macau",
	"MK": "Makedonien",
	"MG": "Madagaskar",
	"MW": "Malawi",
	"MY": "Malaysia",
	"MV": "Maldiverna",
	"ML": "Mali",
	"MT": "Malta",
	"MH": "Marshallöarna",
	"MQ": "Martinique",
	"MR": "Mauretanien",
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Mexiko",
	"FM": "Mikronesien",
	"MD": "Moldavien",
	"MC": "Monaco",
	"MN": "Mongoliet",
	"MS": "Montserrat",
	"MA": "Marocko",
	"MZ": "Moçambique",
	"MM": "Burma",
	"NA": "Namibia",
	"NR": "Nauru",
	"NP": "Nepal",
	"NL": "Nederländerna",
	"NC": "Nya Kaledonien",
	"NZ": "Nya Zeeland",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"NU": "Nioue",
	"NF": "Norfolk ö",
	"MP": "Nordmarianerna",
	"NO": "Norge",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PS": "Välja",
	"PA": "Panama",
	"PG": "Papua Nya Guinea",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Filippinerna",
	"PN": "Pitcairnöarna",
	"PL": "Polen",
	"PT": "Portugal",
	"PR": "Puerto Rico",
	"QA": "Qatar",
	"RE": "Réunion",
	"RO": "Rumänien",
	"RU": "Ryssland",
	"RW": "Rwanda",
	"SH": "Saint Helena",
	"KN": "Saint Kitts och Nevis",
	"LC": "Saint Lucia",
	"PM": "Saint Pierre och Miquelon",
	"VC": "Saint Vincent och Grenadinerna",
	"WS": "Samoa",
	"SM": "San Marino",
	"ST": "São Tomé och Príncipe",
	"SA": "Saudiarabien",
	"SN": "Senegal",
	"SC": "Seychellerna",
	"SL": "Sierra Leone",
	"SG": "Singapore",
	"SK": "Slovakien ",
	"SI": "Slovenien",
	"SB": "Salomonöarna",
	"SO": "Somalia",
	"ZA": "Sydafrika",
	"GS": "Sydgeorgien och Sydsandwichöarna",
	"ES": "Spanien",
	"LK": "Sri Lanka",
	"SD": "Sudan",
	"SR": "Surinam",
	"SJ": "Svalbard och Jan Mayen",
	"SZ": "Swaziland",
	"SE": "Sverige",
	"CH": "Schweiz",
	"SY": "Syrien",
	"TW": "Taiwan",
	"TJ": "Tadjikistan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TL": "Östtimor",
	"TG": "Togo",
	"TK": "Tokelaou",
	"TO": "Tonga",
	"TT": "Trinidad och Tobago",
	"TN": "Tunisien",
	"TR": "Turkiet",
	"TM": "Turkmenistan",
	"TC": "Turks- och Caicosöarna",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Ukraina",
	"AE": "Förenade Arabemiraten",
	"GB": "Storbritannien ",
	"US": "USA",
	"UM": "Förenta staternas mindre öar i Oceanien och Västindien",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"VG": "Brittiska Jungfruöarna",
	"VI": "Amerikanska Jungfruöarna",
	"WF": "Wallis - och Futunaöarna",
	"EH": "Västsahara",
	"YE": "Jemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
	"AX": "Åland",
	"BQ": "Karibien Nederländerna",
	"CW": "Curaçao",
	"GG": "Guernsey",
	"IM": "Isle of Man",
	"JE": "Jersey",
	"ME": "Montenegro",
	"BL": "Saint-Barthélemy",
	"MF": "Saint-Barthélemy (franska Antillerna)",
	"RS": "Serbien",
	"SX": "Sint Maarten",
	"SS": "Sydsudan"
};

exports.i18n = function() {
	"use strict";
	return i18n;
};
